### ISSUE TITLE
Transformer not working when rest-cache is enabled

### ISSUE THREAD

**Issue by orvad** [ComfortablyCoding/strapi-plugin-transformer#29]
Hi

Thanks for an awesome plugin :-)

I just wanted to let you know that I have submitted this issue: https://github.com/strapi-community/strapi-plugin-rest-cache/issues/25

The gist of it is this: "When using strapi-plugin-transformer and rest-cache plugin only the first request from api is transformed. Subsequent and therefore cached api requests are not transformed".

I'm guessing it mostly has to do with rest-cache plugin not taking transformer in to account, but I don't know.

**Comment by ntarandek** [comment]
It seems that, in the end, it is the transformer issue - well, sort of :)

I poked around the code and saw that middleware/transform.js has a isAPIRequest call.
Makes sense to check and block other calls - but, nevertheless, I have tried to comment it out - and voila. Works.
After that I tried to console.log the type of the call, just to scratch my itch - since it it obvious that cached call is not of expected "content-api".

And yes, first call gives me this log entry:
`isAPIRequest content-api`

and cached responses give this:
`isAPIRequest admin`

So - when cached data is returned, transformer simply ignores it.

**Comment by ComfortablyCoding** [comment]
I will need to think on this some more but to me I see a few potential solutions (other suggestions are more than welcome). 

1. update the `isAPIRequest` function to be more flexible as suggested above.

2. add a config setting for whitelisting certain requests. Most likely a function that has the route passed and must return a boolean.

3. rest-cache is updated to cache the response after transformer (or any other response manipulating plugin) has completed.


P.S.
I don't want to make changes for specific plugins as who knows how many others can potentially cause issues as well.

**Comment by DevRik99** [comment]
La solución temporal que encontre es copiar el node_modules/strapi-plugin-transformer al la carpeta src del proyecto, deberia de quedar de esta forma src/strapi-plugin-transformer, modificar el siguiente archivo src\strapi-plugin-transformer\server\util\isAPIRequest.js
con el siguiente codigo 
`const isAPIRequest = (ctx) => {
const check = ctx?.state?.route
console.log("isAPIRequest", typeof(check.handler), check)
return typeof(check.handler) === "function" || (typeof(check.handler) === "string" && check.handler.indexOf("api::") !== -1)
}`
Y en el archivo de config\plugins.js aplicar este cambio
` 
{
...,
transformer: {
     enabled: true,
     config: {
       prefix: "/api/",
       responseTransforms: {
         removeAttributesKey: true,
         removeDataKey: true,
       },
     },
     resolve: "./src/strapi-plugin-transformer",
   },
}
`

**Comment by ComfortablyCoding** [comment]
Looks like this was "fixed" on the cache plugins side via [#35](https://github.com/strapi-community/strapi-plugin-rest-cache/pull/35).
