### ISSUE TITLE
[FR] add transformation support for plugin APIs

### ISSUE THREAD

**Issue by maurice-ellis** [ComfortablyCoding/strapi-plugin-transformer#77]
Hi, love this plugin, but it doesn't transform content types from plugins. Is there a reason why?

**Comment by ComfortablyCoding** [comment]
Plugins are not guarunteed to adhere to the core api format and certain plugins (content manager, content builder etc) should not be transformed as theywill potentially break the admin. Due to these reasons at the moment by default all plugins are excluded from transformation. I do plan on adding a configuration option for whitelisting specific plugins, but no ETA.

**Comment by vharadkou** [comment]
Can you please work on it? Version 2.2.0 supported custom plugin transformation. For example, I am using strapi-plugin-slugify and on version 3.0.0 "attributes" property is not removed. But once again, it's working fine on version 2.2.0 of strapi-plugin-transformer.

Any comment on why you removed previously worked functionality??

**Comment by ComfortablyCoding** [comment]
Sorry, been sick for the last week or so. This should be fixed by #82 , still needs a bit of testing but plan to merge over the weekend. Feel free to test it out.

**Comment by ComfortablyCoding** [comment]
This should now be possible in v3.1.0 via #82

**Comment by vharadkou** [comment]
@ComfortablyCoding, thank you for the update. It's working!
